### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by paoludecaic** [xuanli199/weekly#3]
要不弄个分类吧，把这么多期的内容都放到README里，太过于臃肿了
README就做一个索引，然后把每一期的视频内容单开一个文件夹或markdown文档做一个小分类吧

**Comment by ymfqa** [comment]
赞同，可以参照第26期视频里面另外两个周报项目，每期视频的内容单独放在一个md文件里

**Comment by xuanli199** [comment]
已修改
