### ISSUE TITLE
谁能告诉我，玄离舅舅是不是女孩纸

### ISSUE THREAD

**Issue by Uwith** [xuanli199/weekly#4]

**Comment by jalaxy33** [comment]
他们之前专门出视频回答过这个问题：https://www.bilibili.com/video/BV1Q24y1o7im/

**Comment by lsinda** [comment]
【请问UP你是男的，还是女的？】 https://www.bilibili.com/video/BV1Q24y1o7im/?share_source=copy_web&vd_source=986bed7f72c7ac14ced77cdbda1ab4e2

**Comment by paoludecaic** [comment]
看前几个issue推的22年的视频，这是个团队号

**Comment by wyf9** [comment]
> 【请问UP你是男的，还是女的？】 https://www.bilibili.com/video/BV1Q24y1o7im/?share_source=copy_web&vd_source=986bed7f72c7ac14ced77cdbda1ab4e2

温馨提示：`vd_source` 包含分享者信息哦

**Comment by XiaoYangTech** [comment]
> 看前几个issue推的22年的视频，这是个团队号

团队已经散了哦，她自己一个人做视频的

**Comment by XiaoYangTech** [comment]
> 他们之前专门出视频回答过这个问题：https://www.bilibili.com/video/BV1Q24y1o7im/

团队已散，她自己一个人做视频了

**Comment by yrljroli** [comment]
> > 【请问UP你是男的，还是女的？】 https://www.bilibili.com/video/BV1Q24y1o7im/?share_source=copy_web&vd_source=986bed7f72c7ac14ced77cdbda1ab4e2
> 
> 温馨提示：`vd_source` 包含分享者信息哦

目前而言、好像还是无法解密的密文吧。不过确实推荐止分享到av／bv号截止。
